- image:
    name: "image-registry.vo.elte.hu/report-v9"
    command: "/entrypoint.sh"
    description: "Image for reports that need only extra python packages"
    os: "Ubuntu 24.04"
    app: "Jupyter and Python"
    hardware: "CPU only"
    packages: "flask"
    image_type: "reportimage"
      #    proxy:
      #      jupyter:
      #           token: True
      #           default: True
      #           port: 8000
      #      testurl:
      #           token: False
      #           default: False
      #           port: 9000
