FROM base-jupyterlab_ubuntu20-v6

# SLURM 
RUN pip install jupyterlab_slurm pandas

RUN  $CONDA_DIR/bin/conda install -c conda-forge  jupyterlab-git
#RUN  $CONDA_DIR/bin/conda install -c conda-forge jupyterlab-lsp jupyter-lsp-python 



